/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2014-05-25 06:04:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addEmployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"miscCss.css\"/>\r\n");
      out.write("<title>ADD EMPLOYEE</title>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("<!-- \r\n");
      out.write("function openWinPosts(){\r\n");
      out.write("\tw1=window.open('posts.html',height=120,'Posts',\"toolbar=no, menubar=no, width=250px, height=551px, resizable=no\");\r\n");
      out.write("}\r\n");
      out.write("// -->\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("<!-- \r\n");
      out.write("function openWinDids(){\r\n");
      out.write("\tw1=window.open('dids.html',height=120,'Dids',\"toolbar=no, menubar=no, width=250px, height=551px, resizable=no\");\r\n");
      out.write("}\r\n");
      out.write("// -->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headerPage.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminMenu.jsp", out, false);
      out.write("\r\n");
      out.write("<div style=\"text-align:center;font-size:20px;font-weight: 600;padding-bottom: 50px;\">ADD EMPLOYEE</div>\r\n");
      out.write("<form action=\"addEmployee\" method=\"post\" name=\"empFrm\" >\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("<tr><td>ID*</td><td><input type=\"text\" name=\"eid\" /></td></tr>\r\n");
      out.write("<tr><td>Name*</td><td><input type=\"text\" name=\"ename\" /></td></tr>\r\n");
      out.write("<tr><td>Date of Birth*</td><td><input type=\"date\" name=\"dob\" placeholder=\"yyyy-mm-dd\" /></td></tr>\r\n");
      out.write("<tr><td>Date of Joining*</td><td><input type=\"date\" name=\"doj\" placeholder=\"yyyy-mm-dd\" /></td></tr>\r\n");
      out.write("<tr><td>Post*</td><td><input type=\"text\" name=\"position\" ondblclick=\"openWinPosts()\"/></td></tr>\r\n");
      out.write("<tr><td>Department ID*</td><td><input type=\"text\" name=\"deptid\" ondblclick=\"openWinDids()\" /></td></tr>\r\n");
      out.write("<tr><td>Salary*</td><td><input type=\"number\" name=\"salary\"/></td></tr>\r\n");
      out.write("<tr><td>Contact Number</td><td><input type=\"text\" name=\"contact\"/></td></tr>\r\n");
      out.write("<tr><td>E-mail</td><td><input type=\"text\" name=\"email\"/></td></tr>\r\n");
      out.write("<tr><td>Address*</td><td><input type=\"text\" name=\"address\"/></td></tr>\r\n");
      out.write("<tr><td><br/></td></tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"Add\" /></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<span>* mandatory</span>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footerPage.jsp", out, false);
      out.write('\r');
      out.write('\n');

Integer State=0;
HttpSession session_addEmployee = request.getSession();
session_addEmployee.setAttribute("State", State);

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
