/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2014-05-24 22:43:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"indexLoginCss.css\" />\r\n");
      out.write("<title>WELCOME TO OLMS</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<div id=\"head_container\">\r\n");
      out.write("<div id=\"logo\"><img src=\"logo.png\"/></div>\r\n");
      out.write("<div id=\"banner\">\r\n");
      out.write("  <div id=\"header21\">Lalit Narayana Mishra College of Business Management</div>\r\n");
      out.write("  <div id=\"header22\">(Affiliated and Approved by UGC & All India Council for Technical Education)</div>\r\n");
      out.write("  <div id=\"header23\">An Autonomous College under B. R. Ambedkar Bihar University</div>\r\n");
      out.write("  <div id=\"header24\">Muzaffarpur</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"body_container\">\r\n");
      out.write("<div id=\"login_panel\">\r\n");
      out.write("<form action=\"login\" method=\"post\">\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("<tr><td class=\"lgt\">User ID</td><td><input class=\"lgi\" type=\"text\" name=\"uid\" /></td></tr>\r\n");
      out.write("<tr><td class=\"lgt\">Password</td><td><input class=\"lgi\" type=\"password\" name=\"pswd\" /></td></tr>\r\n");
      out.write("<tr><td><br /></td></tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\"><input id=\"lgs\" type=\"submit\" value=\"Login\" /></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\"><a href=\"mailto:lnmcbm@sify.com?subject=Feedback & body= L N Mishra Rocks!!!\">&copy L N Mishra College of Business Management, Bhagwanpur, Muzaffarpur[BIHAR]</a> </div>\r\n");
      out.write("</div>\r\n");

Integer errorState=0;
HttpSession session_login = request.getSession();
session_login.setAttribute("errorState", errorState);

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
